name: my_whatsapp_clone
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  firebase_auth: ^0.18.0+1  
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
  
